Repository smaranjitghose/Full_Stack_Bootcamp, pull requests merged in 2024-12, with the labels that each got.

#50 assignment 1 6 IT A Pranjal
  submissions/mongodb/2203031080144.txt
Labels: 6ITA, assignment-1

#70 Assignment 1 - 6ITA - Harsh Surani
  submissions/mongodb/2203031080123.txt
Labels: 6ITA, assignment-1

#78 assignment1 6ITA Vrushangi
  submissions/mongodb/2203031080222.txt
Labels: 6ITA, assignment-1

#74 Assignment1 - IT6A - DEEP MENPARA
  submissions/mongodb/2203031080091.txt
Labels: 6ITA, assignment-1

#71 Assignment1-6ITA-dhyan
  submissions/mongodb/2203031080216.txt
Labels: 6ITA, assignment-1

#72 IT6A - DEEP MENPARA
  logistics/Student_Info.MD
Labels: 6ITA

#66 Assignment 1 - 6ITA - Vinit
  submissions/mongodb/2203031080139.txt
Labels: 6ITA, assignment-1

#69 Assignment 1 - 6ITA - Ankit kumar
  submissions/mongodb/2203031080184.txt
Labels: 6ITA, assignment-1

#76 Assignment 1 - 6ITA - Sahil
  2203031080235.txt
Labels: 6ITA, assignment-1

#77 Update 2203031080132.txt
  submissions/mongodb/2203031080132.txt
Labels: 6ITA, assignment-1

#64 Update 2203031080131.txt
  submissions/mongodb/2203031080131.txt
Labels: 6ITA, assignment-1

#63 Assignment 1 - 6ITA - Ayush
  submissions/mongodb/2203031080028.txt
Labels: 6ITA, assignment-1

#68 6IT-A - ASSIGNMENT-1 Sprash Patel
  submissions/mongodb/2203031080053.txt
Labels: 6ITA, assignment-1

#75 Assignment1-6ITA-mann
  logistics/Student_Info.MD
  submissions/mongodb/2203031080260.txt
Labels: 6ITA, assignment-1

#111 Assignment 2- 6ITA - Suhani
  submissions/html/assignment1/2203031080160/q1.html
  submissions/html/assignment1/2203031080160/q2.html
  submissions/html/assignment1/2203031080160/q3.html
  submissions/html/assignment1/2203031080160/q4.html
  submissions/html/assignment1/2203031080160/q5.html
Labels: 6ITA, assignment-2

#112 Assignment2 - 6ITA - Mansha
  submissions/html/assignment1/2203031080121/q-1.html
  submissions/html/assignment1/2203031080121/q-2.html
  submissions/html/assignment1/2203031080121/q-4.html
  submissions/html/assignment1/2203031080121/q-5.html
  submissions/html/assignment1/2203031080121/q-6.html
  submissions/html/assignment1/2203031080121/q-7.html
  submissions/html/assignment1/2203031080121/q3.html
Labels: 6ITA, assignment-2

#110 Assignment2 -6ITA- alisha
  submissions/html/assignment1/2203031080202/q1.html
  submissions/html/assignment1/2203031080202/q2.html
  submissions/html/assignment1/2203031080202/q3.html
  submissions/html/assignment1/2203031080202/q4.html
  submissions/html/assignment1/2203031080202/q5.html
Labels: 6ITA, assignment-2

#113 Assignment 2- 6ITA - Ankit kumar
  submissions/html/assignment1/2203031080184/image/profile-pic.png
  submissions/html/assignment1/2203031080184/q1.html
  submissions/html/assignment1/2203031080184/q2.html
  submissions/html/assignment1/2203031080184/q3.html
  submissions/html/assignment1/2203031080184/q4.html
  submissions/html/assignment1/2203031080184/q5.html
  submissions/html/assignment1/submissions.txt
Labels: 6ITA, assignment-2

#107 Assignment2-6ITA-mann
  submissions/html/assignment1/2203031080260/images/mann.jpeg
  submissions/html/assignment1/2203031080260/q1.html
  submissions/html/assignment1/2203031080260/q2.html
  submissions/html/assignment1/2203031080260/q3.html
  submissions/html/assignment1/2203031080260/q4.html
  submissions/html/assignment1/2203031080260/q5.html
Labels: 6ITA, assignment-2

#104 assignment2 -6ITA -Utsav
  submissions/html/assignment1/2203031080002/q1.html
  submissions/html/assignment1/2203031080002/q2.html
  submissions/html/assignment1/2203031080002/q3.html
  submissions/html/assignment1/2203031080002/q4.html
  submissions/html/assignment1/2203031080002/q5.html
Labels: 6ITA, assignment-2

#102 Assignment2 - 6ITA - Vaishnavi
  submissions/html/assignment1/2203031080013/Q1.html
  submissions/html/assignment1/2203031080013/Q2.html
  submissions/html/assignment1/2203031080013/Q3.html
  submissions/html/assignment1/2203031080013/Q4.html
  submissions/html/assignment1/2203031080013/Q5.html
  submissions/html/assignment1/2203031080013/abb.jpg
Labels: 6ITA, assignment-2

#105 Assignment 2- 6ITA - Ayush Vadodariya
  submissions/html/assignment1/2203031080028/q1.html
  submissions/html/assignment1/2203031080028/q2.html
  submissions/html/assignment1/2203031080028/q3.html
  submissions/html/assignment1/2203031080028/q4.html
  submissions/html/assignment1/2203031080028/q5.html
Labels: 6ITA, assignment-2

#106 Assignment2-6ITA-pranjal
  submissions/html/assignment1/2203031080144/Q1.html
  submissions/html/assignment1/2203031080144/Q2.html
  submissions/html/assignment1/2203031080144/Q3.html
  submissions/html/assignment1/2203031080144/Q4.html
  submissions/html/assignment1/2203031080144/Q5.html
Labels: 6ITA, assignment-2

#84 assignment2 -6ITA -Aryan
  submissions/html/assignment1/2203031080125/images/Me.jpg
  submissions/html/assignment1/2203031080125/q1.html
  submissions/html/assignment1/2203031080125/q2.html
  submissions/html/assignment1/2203031080125/q3.html
  submissions/html/assignment1/2203031080125/q4.html
  submissions/html/assignment1/2203031080125/q5.html
Labels: 6ITA, assignment-2

#89 Assignment 2- 6ITA - Harsh Surani
  submissions/html/assignment1/2203031080123/q1.html
  submissions/html/assignment1/2203031080123/q2.html
  submissions/html/assignment1/2203031080123/q3.html
  submissions/html/assignment1/2203031080123/q4.html
  submissions/html/assignment1/2203031080123/q5.html
Labels: 6ITA, assignment-2

#95 assignment 2 6IT A - vishang
  submissions/html/assignment1/2203031080035/images/20241103_090356.jpg
  submissions/html/assignment1/2203031080035/images/Shiv.jpeg
  submissions/html/assignment1/2203031080035/problem1.html
  submissions/html/assignment1/2203031080035/problem2.html
  submissions/html/assignment1/2203031080035/problem3.html
  submissions/html/assignment1/2203031080035/problem4.html
  submissions/html/assignment1/2203031080035/problem5.html
Labels: 6ITA, assignment-2

#114 Assignment2 - 6ITA - Ashish
  submissions/html/assignment1/2203031080161/q-1.html
  submissions/html/assignment1/2203031080161/q-2.html
  submissions/html/assignment1/2203031080161/q-3.html
  submissions/html/assignment1/2203031080161/q-4.html
  submissions/html/assignment1/2203031080161/q-5.html
  submissions/html/assignment1/2203031080161/q-6.html
  submissions/html/assignment1/2203031080161/q-7.html
Labels: 6ITA, assignment-2

#85 Assignment 2- 6ITA - Jenish
  submissions/html/assignment1/2203031080007/q1.html
  submissions/html/assignment1/2203031080007/q2.html
  submissions/html/assignment1/2203031080007/q3.html
  submissions/html/assignment1/2203031080007/q3img.jpg
  submissions/html/assignment1/2203031080007/q4.html
  submissions/html/assignment1/2203031080007/q5.html
  submissions/html/assignment1/2203031080007/q6.html
Labels: 6ITA, assignment-2

#93 Assignment2 - 6ITA - Vignesh
  submissions/html/assignment1/2203031080131/img.jpg
  submissions/html/assignment1/2203031080131/q1.html
  submissions/html/assignment1/2203031080131/q2.html
  submissions/html/assignment1/2203031080131/q3.html
  submissions/html/assignment1/2203031080131/q4.html
  submissions/html/assignment1/2203031080131/q5.html
Labels: 6ITA, assignment-2

#97 Assignment2 - 6ITA - Darsh Kalani
  submissions/html/assignment1/2203031080032/q1.html
  submissions/html/assignment1/2203031080032/q2.html
  submissions/html/assignment1/2203031080032/q3.html
  submissions/html/assignment1/2203031080032/q4.html
  submissions/html/assignment1/2203031080032/q5.html
Labels: 6ITA, assignment-2

#80 Assiement 2 - IT6A - Yash Sakhareliya
  submissions/html/assignment1/2203031080015/images/PHOTO_YASH.jpg
  submissions/html/assignment1/2203031080015/q1.html
  submissions/html/assignment1/2203031080015/q2.html
  submissions/html/assignment1/2203031080015/q3.html
  submissions/html/assignment1/2203031080015/q4.html
  submissions/html/assignment1/2203031080015/q5.html
  submissions/html/assignment1/2203031080015/q6.html
Labels: 6ITA, assignment-2

#100 Assignment 2 6IT-A Sparsh
  submissions/html/assignment1/2203031080053.txt/Q1.html
  submissions/html/assignment1/2203031080053.txt/Q2.html
  submissions/html/assignment1/2203031080053.txt/Q3.html
  submissions/html/assignment1/2203031080053.txt/Q4.html
  submissions/html/assignment1/2203031080053.txt/Q5.html
  submissions/html/assignment1/2203031080053.txt/download.jpeg
Labels: 6ITA, assignment-2

#101 Assignment2-IT6A-Sahil
  submissions/html/assignment1/2203031080235/Q1.html
  submissions/html/assignment1/2203031080235/Q2.html
  submissions/html/assignment1/2203031080235/Q3.html
  submissions/html/assignment1/2203031080235/Q4.html
  submissions/html/assignment1/2203031080235/Q5.html
  submissions/html/assignment1/2203031080235/images/profile.jpeg
Labels: 6ITA, assignment-2

#103 Assignment2-6ITA-dhyan
  submissions/html/assignment1/2203031080216/images/dhyan.png
  submissions/html/assignment1/2203031080216/q1.html
  submissions/html/assignment1/2203031080216/q2.html
  submissions/html/assignment1/2203031080216/q3.html
  submissions/html/assignment1/2203031080216/q4.html
  submissions/html/assignment1/2203031080216/q5.html
Labels: 6ITA, assignment-2

#118 Assignment 2 6ITA Hardeep
  submissions/html/assignment1/2203031080031/images/profile.jpg
  submissions/html/assignment1/2203031080031/q1.html
  submissions/html/assignment1/2203031080031/q2.html
  submissions/html/assignment1/2203031080031/q3.html
  submissions/html/assignment1/2203031080031/q4.html
  submissions/html/assignment1/2203031080031/q5.html
Labels: 6ITA, assignment-2

#119 Assignment 2-6ITA-Ravi Vira
  submissions/html/assignment1/2203031080018/q1.html
  submissions/html/assignment1/2203031080018/q2.html
  submissions/html/assignment1/2203031080018/q3.html
  submissions/html/assignment1/2203031080018/q4.html
  submissions/html/assignment1/2203031080018/q5.html
Labels: 6ITA, assignment-2

#121 Assignment 2- 6ITA - Vinit Patel
  submissions/html/assignment1/2203031080139/q1.html.html
  submissions/html/assignment1/2203031080139/q2.html.html
  submissions/html/assignment1/2203031080139/q3.html.html
  submissions/html/assignment1/2203031080139/q4.html.html
  submissions/html/assignment1/2203031080139/q5.html.html
  submissions/html/assignment1/2203031080139/vinu.jpg
Labels: 6ITA, assignment-2

#116 Assignment 2 IT6A MEET PATEL
  submissions/html/assignment1/2203031080011/README.md
  submissions/html/assignment1/2203031080011/q1.html
  submissions/html/assignment1/2203031080011/q2.html
  submissions/html/assignment1/2203031080011/q3.html
  submissions/html/assignment1/2203031080011/q4.html
  submissions/html/assignment1/2203031080011/q5.html
Labels: 6ITA, assignment-2

#87 6IT-A Rajdeepsinh
  .github/ISSUE_TEMPLATE/assignment.md
  .github/PULL_REQUEST_TEMPLATE/assignment_pr.md
  submissions/html/assignment1/2203031080069/a1.html
  submissions/html/assignment1/2203031080069/a2.html
  submissions/html/assignment1/2203031080069/q1.html
  submissions/html/assignment1/2203031080069/q2.html
  submissions/html/assignment1/2203031080069/q3.html
  submissions/html/assignment1/2203031080069/q4.html
  submissions/html/assignment1/2203031080069/q5.html
  submissions/html/assignment1/2203031080069/user.png
Labels: 6ITA, assignment-2

#117 Assigement-2 IT6-A Pranav
  submissions/html/assignment1/2303031087022/problem10.html
  submissions/html/assignment1/2303031087022/problem11.html
  submissions/html/assignment1/2303031087022/problem12.html
  submissions/html/assignment1/2303031087022/problem6.html
  submissions/html/assignment1/2303031087022/problem7.html
  submissions/html/assignment1/2303031087022/problem8.html
  submissions/html/assignment1/2303031087022/problem9.html
  submissions/html/assignment1/2303031087022/q1.html
  submissions/html/assignment1/2303031087022/q2.html
  submissions/html/assignment1/2303031087022/q3.html
  submissions/html/assignment1/2303031087022/q4.html
  submissions/html/assignment1/2303031087022/q5.html
Labels: 6ITA, assignment-2

#129 Assignment 2B 6ITA Hani
  submissions/html/assignment1/2303031087088/ex1.html
  submissions/html/assignment1/2303031087088/ex2.html
  submissions/html/assignment1/2303031087088/ex3.html
  submissions/html/assignment1/2303031087088/ex4.html
  submissions/html/assignment1/2303031087088/ex5.html
  submissions/html/assignment1/2303031087088/ex6.html
  submissions/html/assignment1/2303031087088/ex7.html
  submissions/html/assignment1/2303031087088/ex8.html
  submissions/html/assignment1/2303031087088/q1.html
  submissions/html/assignment1/2303031087088/q2.html
  submissions/html/assignment1/2303031087088/q3.html
  submissions/html/assignment1/2303031087088/q4.html
  submissions/html/assignment1/2303031087088/q5.html
Labels: 6ITA, assignment-2

#126 Assignment2-6ITA Satyam
  submissions/html/assignment1/2203031080232/AssignmentQ1.html
  submissions/html/assignment1/2203031080232/AssignmentQ2.html
  submissions/html/assignment1/2203031080232/AssignmentQ3.html
  submissions/html/assignment1/2203031080232/AssignmentQ4.html
  submissions/html/assignment1/2203031080232/AssignmentQ5.html
Labels: 6ITA, assignment-2

#125 Assignment2-6ITA-Rishabh
  submissions/html/assignment1/2203031080114/Ex1.html
  submissions/html/assignment1/2203031080114/Ex2.html
  submissions/html/assignment1/2203031080114/Ex3.html
  submissions/html/assignment1/2203031080114/Ex4.html
  submissions/html/assignment1/2203031080114/Ex5.html
Labels: 6ITA, assignment-2

#131 Assignment 2B 6ITA Hardeep Ijardar
  submissions/html/assignment1/2203031080031/aq1.html
  submissions/html/assignment1/2203031080031/aq2.html
  submissions/html/assignment1/2203031080031/aq3.html
  submissions/html/assignment1/2203031080031/aq4.html
  submissions/html/assignment1/2203031080031/aq5.html
  submissions/html/assignment1/2203031080031/aq6.html
  submissions/html/assignment1/2203031080031/aq7.html
  submissions/html/assignment1/2203031080031/aq8.html
Labels: 6ITA, assignment-2

#135 Assignment 2B 6IT A - Vishang
  submissions/html/assignment1/2203031080035/problem10.html
  submissions/html/assignment1/2203031080035/problem11.html
  submissions/html/assignment1/2203031080035/problem12.html
  submissions/html/assignment1/2203031080035/problem6.html
  submissions/html/assignment1/2203031080035/problem7.html
  submissions/html/assignment1/2203031080035/problem8.html
  submissions/html/assignment1/2203031080035/problem9.html
Labels: 6ITA, assignment-2

#134 Assignment2B - 6ITA - pranjal
  submissions/html/assignment1/2203031080144/AQ1.html
  submissions/html/assignment1/2203031080144/AQ2.html
  submissions/html/assignment1/2203031080144/AQ3.html
  submissions/html/assignment1/2203031080144/AQ4.html
  submissions/html/assignment1/2203031080144/AQ5.html
  submissions/html/assignment1/2203031080144/AQ6.html
  submissions/html/assignment1/2203031080144/AQ7.html
  submissions/html/assignment1/2203031080144/AQ8.html
  submissions/html/assignment1/2203031080144/audio/Small Audio Clip.mp3
  submissions/html/assignment1/2203031080144/images/download.jpeg
  submissions/html/assignment1/2203031080144/images/scenery.jpg
  submissions/html/assignment1/2203031080144/video/Flowers - Video Background HD 1080p.mp4
Labels: 6ITA, assignment-2

#137 Assignment 2B 6ITA Hardeep Ijardar
  submissions/html/assignment1/2203031080031/aq8.html
Labels: 6ITA, assignment-2

#132 Assigement2-B IT6-A Pranav
  submissions/html/assignment1/2303031087022/problem8.html
Labels: 6ITA, assignment-2

#139 Assignment 2B- 6ITA - Harsh Surani
  submissions/html/assignment1/2203031080123/Aq1.html
  submissions/html/assignment1/2203031080123/Aq2.html
  submissions/html/assignment1/2203031080123/Aq3.html
  submissions/html/assignment1/2203031080123/Aq4.html
  submissions/html/assignment1/2203031080123/Aq5.html
  submissions/html/assignment1/2203031080123/Aq6.html
  submissions/html/assignment1/2203031080123/Aq7.html
  submissions/html/assignment1/2203031080123/Aq8.html
Labels: 6ITA, assignment-2

#124 Assignment2b-6ITA-Neeti
  submissions/html/assignment1/2303031087080/aq1.html
  submissions/html/assignment1/2303031087080/aq2.html
  submissions/html/assignment1/2303031087080/aq3.html
  submissions/html/assignment1/2303031087080/aq4.html
  submissions/html/assignment1/2303031087080/aq5.html
  submissions/html/assignment1/2303031087080/aq6.html
  submissions/html/assignment1/2303031087080/aq7.html
  submissions/html/assignment1/2303031087080/aq8.html
  submissions/html/assignment1/2303031087080/q1.html
  submissions/html/assignment1/2303031087080/q2.html
  submissions/html/assignment1/2303031087080/q3.html
  submissions/html/assignment1/2303031087080/q4.html
  submissions/html/assignment1/2303031087080/q5.html
Labels: 6ITA, assignment-2

#145 Assignment 2- 6ITA - Vinit Patel
  submissions/html/assignment1/2203031080139/Aq1.html
  submissions/html/assignment1/2203031080139/Aq2.html
  submissions/html/assignment1/2203031080139/Aq3.html
  submissions/html/assignment1/2203031080139/Aq4.html
  submissions/html/assignment1/2203031080139/Aq5.html
  submissions/html/assignment1/2203031080139/Aq6.html
  submissions/html/assignment1/2203031080139/Aq7.html
  submissions/html/assignment1/2203031080139/Aq8.html
Labels: 6ITA, assignment-2

#143 Assignment2B 6ITA Raj Patel
  submissions/html/assignment1/2203031080069/2203031080123/q1.html
  submissions/html/assignment1/2203031080069/2203031080123/q2.html
  submissions/html/assignment1/2203031080069/2203031080123/q3.html
  submissions/html/assignment1/2203031080069/2203031080123/q4.html
  submissions/html/assignment1/2203031080069/2203031080123/q5.html
  submissions/html/assignment1/2203031080105/advance1.html
  submissions/html/assignment1/2203031080105/advance2.html
  submissions/html/assignment1/2203031080105/advance3.html
  submissions/html/assignment1/2203031080105/advance4.html
  submissions/html/assignment1/2203031080105/advance5.html
  submissions/html/assignment1/2203031080105/advance6.html
  submissions/html/assignment1/2203031080105/advance7.html
  submissions/html/assignment1/2203031080105/advance8.html
  submissions/html/assignment1/2203031080105/q1.html
  submissions/html/assignment1/2203031080105/q2.html
  submissions/html/assignment1/2203031080105/q3.html
  submissions/html/assignment1/2203031080105/q4.html
  submissions/html/assignment1/2203031080105/q5.html
Labels: 6ITA, assignment-2

#164 Assignment 2B 6IT-A - Ayush Vadodariya
  submissions/html/assignment1/2203031080028/Aq1.html
  submissions/html/assignment1/2203031080028/Aq2.html
  submissions/html/assignment1/2203031080028/Aq3.html
  submissions/html/assignment1/2203031080028/Aq4.html
  submissions/html/assignment1/2203031080028/Aq5.html
  submissions/html/assignment1/2203031080028/Aq7.html
  submissions/html/assignment1/2203031080028/Aq8.html
Labels: 6ITA, assignment-2

#165 Assignment 2B 6IT-A - Mann Solanki
  submissions/html/assignment1/2203031080260/Aq1.html
  submissions/html/assignment1/2203031080260/Aq2.html
  submissions/html/assignment1/2203031080260/Aq3.html
  submissions/html/assignment1/2203031080260/Aq4.html
  submissions/html/assignment1/2203031080260/Aq5.html
  submissions/html/assignment1/2203031080260/Aq6.html
  submissions/html/assignment1/2203031080260/Aq7.html
  submissions/html/assignment1/2203031080260/Aq8.html
Labels: 6ITA, assignment-2

#167 Assignment 2B 6IT-A - Ankit kumar
  submissions/html/assignment1/2203031080184/Aq1.html
  submissions/html/assignment1/2203031080184/Aq2.html
  submissions/html/assignment1/2203031080184/Aq3.html
  submissions/html/assignment1/2203031080184/Aq4.html
  submissions/html/assignment1/2203031080184/Aq5.html
  submissions/html/assignment1/2203031080184/Aq6.html
  submissions/html/assignment1/2203031080184/Aq7.html
  submissions/html/assignment1/2203031080184/Aq8.html
Labels: 6ITA, assignment-2

#162 Assignment 2B 6IT-A - Darsh Kalani
  submissions/html/assignment1/2203031080032/aq1.html
  submissions/html/assignment1/2203031080032/aq2.html
  submissions/html/assignment1/2203031080032/aq3.html
  submissions/html/assignment1/2203031080032/aq4.html
  submissions/html/assignment1/2203031080032/aq5.html
  submissions/html/assignment1/2203031080032/aq6.html
  submissions/html/assignment1/2203031080032/aq7.html
  submissions/html/assignment1/2203031080032/aq8.html
Labels: 6ITA, assignment-2

#148 assignment 2B 6IT - Sparsh Patel
  submissions/html/assignment1/2203031080053(1)/AQ1.html
  submissions/html/assignment1/2203031080053(1)/AQ2.html
  submissions/html/assignment1/2203031080053(1)/AQ3.html
  submissions/html/assignment1/2203031080053(1)/AQ4.html
  submissions/html/assignment1/2203031080053(1)/AQ5.html
  submissions/html/assignment1/2203031080053(1)/AQ6.html
  submissions/html/assignment1/2203031080053(1)/AQ7.html
Labels: 6ITA, assignment-2

#168 Assignment 2B-6ITA MEET PATEL
  submissions/html/assignment1/2203031080011/Aq1.html
  submissions/html/assignment1/2203031080011/Aq2.html
  submissions/html/assignment1/2203031080011/Aq3.html
  submissions/html/assignment1/2203031080011/Aq4.html
  submissions/html/assignment1/2203031080011/Aq5.html
  submissions/html/assignment1/2203031080011/Aq6.html
  submissions/html/assignment1/2203031080011/Aq7.html
  submissions/html/assignment1/2203031080011/Aq8.html
Labels: 6ITA, assignment-2

#169 Assignment 2B-6ITA-ravi
  submissions/html/assignment1/2203031080018/Aq1.html
  submissions/html/assignment1/2203031080018/Aq2.html
  submissions/html/assignment1/2203031080018/Aq3.html
  submissions/html/assignment1/2203031080018/Aq4.html
  submissions/html/assignment1/2203031080018/Aq5.html
  submissions/html/assignment1/2203031080018/Aq6.html
  submissions/html/assignment1/2203031080018/Aq7.html
  submissions/html/assignment1/2203031080018/Aq8.html
Labels: 6ITA, assignment-2

#171 Assignment 2B-6ITA-dhyan
  submissions/html/assignment1/2203031080216/Aq1.html
  submissions/html/assignment1/2203031080216/Aq2.html
  submissions/html/assignment1/2203031080216/Aq3.html
  submissions/html/assignment1/2203031080216/Aq4.html
  submissions/html/assignment1/2203031080216/Aq5.html
  submissions/html/assignment1/2203031080216/Aq6.html
  submissions/html/assignment1/2203031080216/Aq7.html
  submissions/html/assignment1/2203031080216/Aq8.html
Labels: 6ITA, assignment-2

#174 Assignment2B - 6ITA - Yash Sakhareliya
  submissions/html/assignment1/2203031080015/Aq2.html
  submissions/html/assignment1/2203031080015/Aq3.html
  submissions/html/assignment1/2203031080015/Aq4.html
  submissions/html/assignment1/2203031080015/Aq5.html
  submissions/html/assignment1/2203031080015/Aq6.html
  submissions/html/assignment1/2203031080015/Aq7.html
  submissions/html/assignment1/2203031080015/Aq8.html
  submissions/html/assignment1/2203031080015/aq1.html
  submissions/html/assignment1/2203031080015/images/PHOTO_YASH.jpg
Labels: 6ITA, assignment-2

#176 Assignment 2B - 6ITA - Jenish
  submissions/html/assignment1/2203031080007/aq1.html
  submissions/html/assignment1/2203031080007/aq2.html
  submissions/html/assignment1/2203031080007/aq3.html
  submissions/html/assignment1/2203031080007/aq4.html
  submissions/html/assignment1/2203031080007/aq5.html
  submissions/html/assignment1/2203031080007/aq6.html
  submissions/html/assignment1/2203031080007/aq7.html
  submissions/html/assignment1/2203031080007/aq8.html
Labels: 6ITA, assignment-2

#154 Assignment 2B- 6ITA - Utsav
  submissions/html/assignment1/2203031080002/Aq1.html
  submissions/html/assignment1/2203031080002/Aq2.html
  submissions/html/assignment1/2203031080002/Aq3.html
  submissions/html/assignment1/2203031080002/Aq4.html
  submissions/html/assignment1/2203031080002/Aq5.html
  submissions/html/assignment1/2203031080002/Aq6.html
  submissions/html/assignment1/2203031080002/Aq7.html
  submissions/html/assignment1/2203031080002/Aq8.html
  submissions/html/assignment1/2203031080002/q1.html.html
  submissions/html/assignment1/2203031080002/q2.html.html
  submissions/html/assignment1/2203031080002/q3.html.html
  submissions/html/assignment1/2203031080002/q4.html.html
  submissions/html/assignment1/2203031080002/q5.html.html
Labels: 6ITA, redo, assignment-2

#181 Assignment 2B- 6ITA - Rajdeep
  submissions/html/assignment1/2203031080069/a3.html
  submissions/html/assignment1/2203031080069/a4.html
  submissions/html/assignment1/2203031080069/a5.html
  submissions/html/assignment1/2203031080069/a6.html
  submissions/html/assignment1/2203031080069/a7.html
  submissions/html/assignment1/2203031080069/a8.html
Labels: 6ITA, assignment-2

#161 Assignment 2- 6ITA - Suhani
  submissions/html/assignment1/2203031080160/Aq1.html
  submissions/html/assignment1/2203031080160/Aq2.html
  submissions/html/assignment1/2203031080160/Aq3.html
  submissions/html/assignment1/2203031080160/Aq4.html
  submissions/html/assignment1/2203031080160/Aq5.html
  submissions/html/assignment1/2203031080160/Aq6.html
  submissions/html/assignment1/2203031080160/Aq7.html
  submissions/html/assignment1/2203031080160/Aq8.html
  submissions/html/assignment1/2203031080160/q3.html
  submissions/html/assignment1/2203031080160/q5.html
Labels: 6ITA, assignment-2

#183 Assignment-3 6ITA Hardeep Ijardar
  submissions/mongodb2/2203031080031.txt
Labels: 6ITA, assignment-3

#180 Assignment -3 6IT-A vishang
  submissions/mongodb2/2203031080035.txt
Labels: 6ITA, assignment-3

#189 Assignment 3 - 6ITA - Jenish
  submissions/mongodb2/2203031080007.txt
Labels: 6ITA, assignment-3

#191 Assignment 3 - 6ITA - PranavFaladu
  submissions/mongodb2/2303031087022.txt
Labels: 6ITA, assignment-3

#184 Assignment3-6ITA-Bharvi
  submissions/mongodb2/2303031087002.txt
Labels: 6ITA, assignment-3

#196 Assignment 3 - 6ITA - Bhavin
  submissions/mongodb2/2203031080042.txt
Labels: 6ITA, assignment-3

#195 Assignment 3 - 6ITA - utsav
  submissions/mongodb2/2203031080002.txt
Labels: 6ITA, assignment-3

#198 Assignment-3 6IT-A Ashish Yadav
  submissions/mongodb2/2203031080161.txt
Labels: 6ITA, assignment-3

#193 Assignment3-IT6A-Mansha
  submissions/mongodb2/2203031080121.txt
Labels: 6ITA, assignment-3

#199 assignment1-6ITA-Ravi Vira
  submissions/mongodb/2203031080018.txt
Labels: 6ITA, assignment-1

#203 Assignment 3 - 6ITA - Vignesh
  submissions/mongodb2/2203031080131.txt
Labels: 6ITA, assignment-3

#201 Assignment3-6ITA-Vinit Patel
  submissions/mongodb2/2203031080139.txl
Labels: 6ITA, assignment-3

#202 Assignment3 -6ITA-Suhani
  submissions/mongodb2/2203031080160.txt
Labels: 6ITA, assignment-3

#204 Assignment3-IT6A-Hani
  submissions/mongodb2/2303031087088.txt
Labels: 6ITA, assignment-3

#188 Assignment 3 - 6ITA - Yash Sakhareliya
  submissions/mongodb2/2203031080015.txt
Labels: 6ITA, assignment-3

#205 Assignment 3 - 6ITA - Sahil
  submissions/mongodb2/2203031080235.txt
Labels: 6ITA, assignment-3

#206 Assignment 3 - 6ITA - Aryan
  submissions/mongodb2/2203031080125.txt
Labels: 6ITA, assignment-3

#209 Assignment3-IT6A-Harsh choudhary
  submissions/mongodb2/2203031080132.txt
Labels: 6ITA, assignment-3

#170 Mr harshchoudhary patch 1
  submissions/html/assignment1/2203031080132/Aq1.html
  submissions/html/assignment1/2203031080132/Aq2.html
  submissions/html/assignment1/2203031080132/Aq3.html
  submissions/html/assignment1/2203031080132/Aq4.html
  submissions/html/assignment1/2203031080132/Aq5.html
  submissions/html/assignment1/2203031080132/Aq6.html
  submissions/html/assignment1/2203031080132/Aq7.html
  submissions/html/assignment1/2203031080132/Aq8.html
  submissions/html/assignment1/2203031080132/q1.html
  submissions/html/assignment1/2203031080132/q2.html
  submissions/html/assignment1/2203031080132/q3.html
  submissions/html/assignment1/2203031080132/q4.html
  submissions/html/assignment1/2203031080132/q5.html
Labels: 6ITA, assignment-3

#212 Assignment 3 - 6ITA - Satyam
  submissions/mongodb2/2203031080232.txt
Labels: 6ITA, assignment-3

#211 6ITA - Assignment 2 - Rutuja
  submissions/html/assignment1/ex1.html
  submissions/html/assignment1/ex2.html
  submissions/html/assignment1/ex3.html
  submissions/html/assignment1/ex4.html
  submissions/html/assignment1/ex5.html
  submissions/html/assignment1/ex6.html
  submissions/html/assignment1/ex7.html
  submissions/html/assignment1/ex8.html
  submissions/html/assignment1/q1.html
  submissions/html/assignment1/q2.html
  submissions/html/assignment1/q3.html
  submissions/html/assignment1/q4.html
  submissions/html/assignment1/q5.html
Labels: 6ITA, assignment-2

#213 Asssignment3 -6ITA-Vaishnavi
  submissions/mongodb2/2203031080013.txt
Labels: 6ITA, assignment-3

#220 Assignment 3 - 6ITA - Vignesh
  submissions/mongodb2/2203031080131.txt
Labels: 6ITA, assignment-3

#219 Assignment3-6ITA-Ravi
  submissions/mongodb2/2203031080018.txt
Labels: 6ITA, assignment-3

#223 Assignment 3 IT6A Harsh choudhary
  submissions/mongodb2/2203031080132.txt
Labels: 6ITA, assignment-3

#230 Assignment3 6ITA Mann Solanki
  submissions/mongodb2/2203031080260.txt
Labels: 6ITA, assignment-3

#229 Assignment 3 - 6ITA - Harsh Surani
  submissions/mongodb2/2203031080123.txt
Labels: 6ITA, assignment-3

#221 Assignment 3 - 6ITA - Vrushangi
  submissions/mongodb2/2203031080222.txt
Labels: 6ITA, assignment-3

#228 Assignment 3 - 6ITA - Ayush Vadodariya
  submissions/mongodb2/2203031080028.txt
Labels: 6ITA, assignment-3

#224 2203031080235.txt
  submissions/mongodb2/2203031080235.txt
Labels: 6ITA, assignment-3

#222 Assignment 3 - 6ITA - Satyam
  submissions/mongodb2/2203031080232.txt
Labels: 6ITA, assignment-3

#243 Assignment4 - 6ITA - Jenish
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#233 Assignment-4 6ITA Hardeep Ijardar
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#241 Assignment4 - 6ITA - Yash sakhareliya
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#217 Assignment-1 IT6A Meet Patel
  submissions/mongodb/2203031080011.txt
Labels: 6ITA, assignment-1

#244 Assignment-4 6ITA Darsh Kalani
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#261 Assignment-3 6IT-A Raj Patel
  submissions/mongodb2/2203031080105.txt
Labels: 6ITA, assignment-3

#254 Assignment4 - 6ITA - Raj Patel
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#246 Assignment4 - 6 ITA- Alisha Kaur
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#247 Assignment4 - 6ITA - Rajdeepsinh
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#240 Assignment4 - 6ITA Bhavin
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#262 Assignment4 - 6ITA - Vignesh
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#252 Assignment4 -6ITA-Vaishnavi
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#258 Assignment4-6ITA - Deep Menpara
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#256 Assignment4 - 6ITA - Utsav
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#263 Assignment4 IT6A-Harsh choudhary
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#275 Assignment-4 6ITA Rishabh Rai
  submissions/js/task_1_2.MD
  submissions/mongodb2/2203031080114.txt
Labels: 6ITA, assignment-3, assignment-4

#253 Assignment4 - IT6A - Aryan
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#239 Assignment 4-ITA-Hani
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#269 Assignment-5 6ITA Hardeep Ijardar
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#278 Assignment5 6ITA Bhavin
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#277 Assignment5- 6ITA - Harsh Surani
  submissions/js/task_3_4.MD
Labels: assignment-1, assignment-5

#276 Assignment 5 IT6-A Hani
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#270 Assigement 5 IT6-A Pranav Faladu
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#310 Assignment 4 -IT6A-NeetiDarji
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#282 Assignment 5 - 6ITA- Neeti
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#273 Assignment-5 6ITA Vishang Lad
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#259 assignment4 - 6ITA- vinit
  submissions/js/task_1_2.MD
  submissions/mongodb2/2203031080139.txl
Labels: 6ITA, assignment-4

#284 Assignment5- 6ITA - Utsav
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#321 Assignment-6 6ITA vishang
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#315 Assignment4- 6ITA - dhyan
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#272 Assignment 2B-6ITA-meet
  submissions/html/assignment1/2203031080146/Aq1.html
  submissions/html/assignment1/2203031080146/Aq2.html
  submissions/html/assignment1/2203031080146/Aq3.html
  submissions/html/assignment1/2203031080146/Aq4.html
  submissions/html/assignment1/2203031080146/Aq5.html
  submissions/html/assignment1/2203031080146/Aq6.html
  submissions/html/assignment1/2203031080146/Aq7.html
  submissions/html/assignment1/2203031080146/Aq8.html
  submissions/html/assignment1/2203031080146/images/MEET.jpg
  submissions/html/assignment1/2203031080146/q1.html
  submissions/html/assignment1/2203031080146/q2.html
  submissions/html/assignment1/2203031080146/q3.html
  submissions/html/assignment1/2203031080146/q4.html
  submissions/html/assignment1/2203031080146/q5.html
Labels: 6ITA, assignment-2

#318 Assignment-4 IT-6-A Mansha
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#323 Assignment-6-ITA-NeetiDarji
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#317 Assignment4 - 6ITA - Ashish
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#296 Assignment5- 6ITA - Ashish
  submissions/js/task_1_2.MD
  submissions/js/task_3_4.MD
Labels: 6ITA, redo, assignment-5

#324 Assignment-6 6ITA Hani
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#326 Assignment6 IT6-A Pranav Faladu
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#325 Assignment4-6ITA-meet
  submissions/js/task_1_2.MD
Labels: 6ITA, assignment-4

#327 Assignment5- 6ITA - dhyan
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#362 Assignment-6 6ITA Hardeep Ijardar
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#335 Assignment6- 6ITA - Yash
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#357 Assignment6-6ITA- Vaishnavi
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#351 Assignment6-ITA-Mansha
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#370 Assignment IT-6A Rajdeepsinh
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#339 Assignment5 - 6ITA - Raj Patel
  submissions/js/task_3_4.MD
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-5

#346 Assignment6- 6ITA - Vignesh
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#340 Assignment6 - 6ITA - Utsav
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#314 Assignment5 - IT6A - Yash
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#285 Assignment 5-IT-6A Mansha
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#289 Assignment5- 6ITA - Aryan D.V.
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#333 Assignment5-6ITA-meet
  submissions/js/task_3_4.MD
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-5

#334 Assignment6- 6ITA - Shubham
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6

#322 Assignment5- 6ITA - Vignesh
  submissions/js/task_3_4.MD
Labels: 6ITA, assignment-5

#332 Assignment6 -6ITA - Bhavin
  submissions/js/task_5_6.MD
Labels: 6ITA, assignment-6
