Repository smaranjitghose/Full_Stack_Bootcamp, pull requests merged in 2025-01, with the labels that each got.

#720 Assignment-12 6IT-A Mansha
  submissions/js/applied-js/oop/2203031080121.js
Labels: 6ITA, assignment-12

#716 Assignment12 - 6ITA - Yash Sakhareliya
  submissions/js/applied-js/oop/2203031080015.js
Labels: 6ITA, assignment-12

#721 Assignment12 - 6ITA - Suhani
  submissions/js/applied-js/oop/2203031080160.js
Labels: 6ITA, assignment-12

#717 assignment 12-6ITA- Ravi
  submissions/js/applied-js/oop/2203031080018.js
Labels: 6ITA, assignment-12

#685 Assignment12 - 6ITA - Shubham
  c
  submissions/js/applied-js/oop/2203031080004.js
Labels: 6ITA, assignment-12

#718 Assignment12 -6ITA - Ashish
  submissions/js/applied-js/oop/2203031080161.js
Labels: 6ITA, assignment-12

#710 Assignment12- 6ITA-Vaishnavi
  submissions/js/applied-js/oop/2203031080013.js
Labels: 6ITA, assignment-12

#689 Assignment 12 - 6ITA - Sparsh Patel
  submissions/js/applied-js/oop/2203031080053.js
Labels: 6ITA, assignment-12

#704 Assignment12-6ITA-alisha
  submissions/js/applied-js/oop/2203031080202.js
Labels: 6ITA, assignment-12

#713 Assignment12 - 6ITA - Aryan
  submissions/js/applied-js/functions/2203031080125.js
  submissions/js/applied-js/oop/2203031080125.js
Labels: 6ITA, assignment-12

#714 Assignment12 - 6ITA - Utsav
  submissions/js/applied-js/oop/2203031080002.js
Labels: 6ITA, assignment-12

#719 Assignment1 -6ITA - Ashish
  submissions/mongodb/2203031080161.txt
Labels: 6ITA, assignment-1

#712 Assignment12-6ITA-VrushangiMistry
  submissions/js/applied-js/oop/2203031080222.js
Labels: 6ITA, assignment-12

#711 Assignment 12 IT6A Meet Patel
  submissions/js/applied-js/oop/2203031080011.js
Labels: 6ITA, assignment-12

#700 Assignment 12-6ITA-Neeti
  submissions/js/applied-js/functions/2303031087080.js
  submissions/js/applied-js/oop/2303031087080.js
Labels: 6ITA, assignment-12

#706 Assignment12 - 6ITA - mann
  submissions/js/applied-js/oop/2203031080260.js
Labels: 6ITA, assignment-12

#701 Assignment12 - 6ITA - Ankit Kumar
  submissions/js/applied-js/oop/2203031080184.js
Labels: 6ITA, assignment-12

#697 Assignment 12 - 6ITA - dhyan
  submissions/js/applied-js/oop/2203031080216.js
Labels: 6ITA, assignment-12

#687 Assignment 12 IT6-A Pranav Faladu
  submissions/js/applied-js/oop/2303031087022.JS
Labels: 6ITA, assignment-12

#594 Surprise Test-1 - 2203031080105
  submissions/surprise_test_1.MD
Labels: 6ITA

#705 2203031080146 - Assignment12-meet
  submissions/js/applied-js/oop/2203031080146.js
Labels: 6ITA, assignment-12

#473 Assignment8-6ITA-Bharvi Valand
  submissions/js/task_9.MD
Labels: 6ITA, assignment-8

#580 Surprise Test 1 - 2203031080125
  submissions/surprise_test_1.MD
Labels: 6ITA, surprise-test-1

#725 Assignment13 - 6ITA - Harsh Surani
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#733 Assignment13 - 6ITA - Bharvi
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#740 Assignment13 -6ITA-Harsh choudhary
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#749 Assignment13 - 6ITA - Vrushangi Mistry
  submissions/nodejs/assignment1.MD
  submissions/surprise_test_1.MD
Labels: 6ITA, assignment-13

#738 Assignment13 - 6ITA - Vignesh
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#729 Assignment13 - 6ITA - Jenish
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#737 Assignment13 - 6ITA - Shubham
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#744 Assignment13 - 6ITA - rishabh
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#753 Assignment10- GenAI - vishang
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#736 Assignment13 - 6ITA - Rutuja
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#727 Assignment13 - 6ITA - Yash
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#755 Assignment13 - 6ITA - Darsh Kalani
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#743 Assignment13 - 6ITA - Satyam Singh
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#731 Assignment13 - 6ITA - Rajdeepsinh
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#760 Assignment-13 6IT-A Mansha
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#726 Assignment 13 - 6IT - vishang
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#728 Assignment13 - 6ITA - Bhavin
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#758 Assignment13-6ITA-Deep Menpara
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#754 Assignment 13 - 6ITA - Sahil
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#741 Assignment13 - 6ITA - Aryan
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#747 Assignment13-6ITA-Ravi
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#761 Assignment 13-6ITA- Vaishnavi
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#764 Assignment10- GenAI - Harsh Surani
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#763 Assignment - 10 IT6-A Pranav Faladu
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-13

#799 Assignment10-GenAI- Ravi
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#793 Assignment10-6ITA-alisha
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#796 Assignment10 - GenAI - Suhani
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#797 Assignment10- GenAI - Ayush Vadodariya
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#780 Assignment1- GenAI - Darsh Kalani
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#792 Assignment10 - GenAI - Yash
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#791 Assignment10 - GenAI - Dhyan
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#786 Assignment10 - GenAI - Vinit
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#795 Assignment 10 GenAi MeetPatel
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#774 Assignment10 IT6A - Harsh choudhary
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#787 Assignment1- GenAI - Aryan
  submissions/GenAI/task_1.MD
Labels: assignment-10

#784 Assignment1- GenAI - Shubham
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#776 Assignment 10 - IT6A - Rutuja
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#790 Assignment 10- GenAI- Vaishnavi
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#772 Assignment10 - GenAI - Vignesh
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#783 Assignment10- GenAI - Utsav
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#773 Assignment - 10 IT6-A Mansha
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#777 Assignment10- GenAI - Vrushangi Mistry
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#770 Assignment-10-6ITA-Neeti
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#785 Assignment10 - GenAI - Ashish
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#794 Assignment10 - GenAI - Deep
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#778 Assignment 10- GenAI - Sahil
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#775 Assignment10GenAI-IT6A-Bharvi
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#766 Assignment-10 6ITA Hardeep Ijardar
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#802 Assignment10 - GenAI - Mann
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#788 Assignment 13 - 6ITA - meet
  submissions/GenAI/task_1.MD
  submissions/nodejs/assignment1.MD
Labels: 6ITA, assignment-13

#816 Assignment-14 6IT - vishang
  submissions/GenAI/task_1.MD
  submissions/GenAI/task_2.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-14

#823 Assignment 14 IT6A Meet Patel
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#803 Assignment14- GenAI - Yash
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#808 Assignment14- GenAI - Vignesh
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#818 Assignment-10 GenAI Ankit Kumar
  submissions/GenAI/task_1.MD
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-10

#831 Assignment15- GenAI - Vignesh
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#810 Assignment14 IT6A: Harsh choudhary
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#833 Assignment14- GenAI - Harsh Surani
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#804 Assignment - 14 IT-6-A Pranav Faladu
  submissions/GenAI/task_2.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-14

#826 Assignment14- GenAI - Neeti
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#829 Assignment - 14 - GenAI - Rutuja
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#825 Assignment14-GenAI-Hani
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#820 Assignment14- GenAI - Pranjal
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#813 Assignment14- GenAI - Satyam
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#835 Assignment14- GenAI - Sahil
  submissions/GenAI/task_2.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-14

#824 Assignment14- GenAI - Deep
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#806 Assignment14- GenAI - Bhavin
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#815 Assignment14- GenAI - Vrushangi Mistry
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#821 Assignment14-6ITA-alisha
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#809 Assignment14- GenAI - Aryan
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#842 Assignment10 - GenAI - Raj
  submissions/GenAI/task_1.MD
Labels: 6ITA, assignment-10

#834 Assignment15- GenAI - Harsh Surani
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#838 Assignment14- GenAI - Ashish
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-10

#852 Assignment14-GenAI - Suhani
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#861 Assignment14 - GenAI - Vinit
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#819 Assignment14- GenAI - Hardeep Ijardar
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#828 Assignment14- GenAI - Ravi
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#857 Assignment15- GenAI - Bhavin
  submissions/GenAI/task_1.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#845 Assignment15- GenAI - Yash
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#850 Assignment15- GenAI - Shubham
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#841 Assignment15 IT6A: Harsh choudhary
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#811 Assignment14- GenAI - Rajdeepsinh
  submissions/GenAI/task_2.MD
Labels: 6ITA, redo, assignment-14

#805 Assignment14- GenAI - Utsav
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#840 Assignment15- GenAI - Jenish
  submissions/GenAI/task_1.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#849 Assignment15- GenAI - Aryan
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#864 Assignment -15 6IT - vishang
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#848 Assignment15- GenAI - Utsav
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#847 Assignment15- GenAI - Rajdeepsinh
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#865 Assignement14 - 6ITA - Pratik Patel
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#830 Assignment14- GenAI - Dhyan
  submissions/GenAI/task_2.MD
Labels: 6ITA, assignment-14

#859 Assignment 14 GenAI- Raj
  submissions/GenAI/task_2.MD
Labels: 6ITA, redo, assignment-14

#869 Assignment15- GenAI - Hardeep Ijardar
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#860 Assignment15- GenAI - Bharvi
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#871 Assignment15- GenAI - Ashish
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#872 Assignment15 -GenAI- Hani
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#870 Assignment15- GenAI - Vrushangi Mistry
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#873 Assignment-15 GenAI Mansha
  submissions/GenAI/task_3.MD
Labels: assignment-15

#836 Assignment14 -GenAI - Mann
  submissions/GenAI/task_2.MD
Labels: 6ITA, redo, assignment-14

#882 Assignment 15-GenAI -Vaishnavi
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#886 Assignment16- GenAI - Yash
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#866 Assignment15- GenAI - Deep
  submissions/GenAI/task_3.MD
Labels: 6ITA, redo, assignment-15

#827 Assignment14- GenAI - Darsh Kalani
  submissions/GenAI/task_2.MD
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-14

#880 Assignment-15 GenAI - Rishabh
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#844 Assignment - 14 - GenAI - Ayush
  submissions/GenAI/task_2.MD
Labels: 6ITA, redo, assignment-14

#908 Assignment16- GenAI - Hardeep Ijardar
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#877 Assignment 15 - GEN AI - Neeti
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#888 Assignment15- GenAI - Pratik Patel
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#879 Assignment16 IT6A- Harsh choudhary
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#867 Assignment15- GenAI - Ravi
  submissions/GenAI/task_3.MD
Labels: 6ITA, redo, assignment-15

#875 Assignment 15 - GenAI - Rutuja
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#890 Assignment16- GenAI - Harsh Surani
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#894 Assignment16- GenAI - Shubham
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#912 Assignment16- GenAI - Pratik Patel
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#917 Assignment 16-GenAI-Neeti
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#901 Assignment15- GenAI - Ankit Kumar
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#904 Assignment-15 GenAI -Mann
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#913 Assignment16- GenAI - Pranjal
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#914 Assignment16-6ITA-alisha
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#884 Assignment15 - GenAI - Suhani
  submissions/GenAI/task_3.MD
Labels: 6ITA, assignment-15

#895 Assignment16- GenAI - Aryan
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#896 Assignment16- GenAI - Utsav
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#899 Assignment16- GenAI - Rajdeepsinh
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#900 Assignment 16 GenAI- Rishabh
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#898 Assignment16- GenAI - Deep
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#903 Assignment16-GenAI-Ravi
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#909 Assignment16- GenAI - Vrushangi Mistry
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16

#922 Assignment16 - GenAI - Vinit
  submissions/GenAI/task_4.MD
Labels: 6ITA, assignment-16
